# Site settings
title: zhelongl
email: 742946057@qq.com
description: "linzhenlong.github.io"
baseurl: ""
url: "linzhenlong.github.io"
twitter_username: linzhenlong
github_username:  linzhenlong

# Build settings
markdown: kramdown
permalink: pretty



comments :

provider : disqus

disqus :

short_name : linzhenlong
